In [189]:
df = pd.read_csv(r'C:\Users\Denis\Downloads\output-onlinexmltools.txt', sep = '\t', encoding = 'utf-8')

In [190]:
df['_TagBased'] = df['_Class']
df['_Class'] = df['_Date']
df['_Date'] = df['_Name']
df['_Name'] = df['_UserId']
df['_UserId'] = df['_Id']
df['_Id'] = df.index

In [191]:
df

,_Id,_UserId,_Name,_Date,_Class,_TagBased
1,1,4,Informed,2016-08-02T15:38:29.913,3,False
2,2,9,Informed,2016-08-02T15:39:20.227,3,False
3,3,16,Informed,2016-08-02T15:39:28.290,3,False
4,4,18,Informed,2016-08-02T15:39:40.377,3,False
5,5,10,Informed,2016-08-02T15:39:56.643,3,False
...,...,...,...,...,...,...
56956,56956,61257,Autobiographer,2022-09-24T18:07:40.790,3,False
56957,56957,61260,Supporter,2022-09-24T18:48:50.723,3,False
56958,56958,61269,Informed,2022-09-25T02:19:46.900,3,False
56959,56959,49023,Supporter,2022-09-25T02:35:30.343,3,False
56960,56960,61270,Editor,2022-09-25T02:41:35.300,3,False

In [192]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\badges.csv', index = False, sep='\t')

In [193]:
df = pd.read_excel(r'C:\Users\Denis\Downloads\Comments.xlsx', engine = 'openpyxl')

In [194]:
df

,_Id,_PostId,_Score,_Text,_CreationDate,_UserId,_ContentLicense,_UserDisplayName
0,9,22,1,I think the AI Box is actually a bad introduct...,2016-08-02T16:00:04.297,10.0,CC BY-SA 3.0,NaN
1,10,15,6,Definitely requires a statistical approach wit...,2016-08-02T16:01:10.020,38.0,CC BY-SA 3.0,NaN
2,11,22,0,Fair enough. I just happen to be more familia...,2016-08-02T16:04:37.090,33.0,CC BY-SA 3.0,NaN
3,14,41,1,If by IQ you mean pattern-finding (which is ge...,2016-08-02T16:14:28.373,47.0,CC BY-SA 3.0,NaN
4,24,45,0,"Regarding Asimov's laws, AFAIK, [the zeroth la...",2016-08-02T16:49:20.210,71.0,CC BY-SA 3.0,NaN
...,...,...,...,...,...,...,...,...
23380,56124,37175,0,"@VladimirZolotov, I don't know of a reference ...",2022-09-23T17:05:02.790,1794.0,CC BY-SA 4.0,NaN
23381,56125,37157,0,Thanks for information. I also wonder if your ...,2022-09-23T18:45:01.367,27229.0,CC BY-SA 4.0,NaN
23382,56126,23377,0,I don't think anybody will try your code befor...,2022-09-24T05:45:53.920,22659.0,CC BY-SA 4.0,NaN
23383,56128,37172,0,"@JaumeOliverLafont Yes, that's right.",2022-09-24T13:43:01.133,60672.0,CC BY-SA 4.0,NaN
23384,56129,37176,0,Does not answer the question (which I think is...,2022-09-24T23:59:41.670,11539.0,CC BY-SA 4.0,NaN

In [195]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Comments.csv', index = False, sep = '\t')

In [196]:
df = pd.read_csv(r'C:\Users\Denis\Downloads\output-onlinexmltools (1).txt', index_col=None, sep = '\t', encoding = 'utf-8')

In [197]:
df

,_Id,_TagName,_Count,_ExcerptPostId,_WikiPostId
2,generalization,35,17536,17535,NaN
4,neurons,25,6022,6021,NaN
8,intelligent-agent,65,1765,1764,NaN
9,philosophy,179,2551,2550,NaN
12,fuzzy-logic,24,252,251,NaN
...,...,...,...,...,...
2671,episodes,1,35844,35843,NaN
2672,ms-pacman,1,undefined,undefined,NaN
2673,bayesian-reinforcement-learning,2,35981,35980,NaN
2675,out-of-distribution-detection,1,undefined,undefined,NaN
2676,energy-based-models,1,undefined,undefined,NaN

In [198]:
df['_WikiPostId'] = df['_ExcerptPostId']
df['_ExcerptPostId'] = df['_Count']
df['_Count'] = df['_TagName']
df['_TagName'] = df['_Id']
df['_Id'] = df.index

In [199]:
df

       _Id                         _TagName  _Count _ExcerptPostId _WikiPostId
2        2                   generalization      35          17536       17535
4        4                          neurons      25           6022        6021
8        8                intelligent-agent      65           1765        1764
9        9                       philosophy     179           2551        2550
12      12                      fuzzy-logic      24            252         251
...    ...                              ...     ...            ...         ...
2671  2671                         episodes       1          35844       35843
2672  2672                        ms-pacman       1      undefined   undefined
2673  2673  bayesian-reinforcement-learning       2          35981       35980
2675  2675    out-of-distribution-detection       1      undefined   undefined
2676  2676              energy-based-models       1      undefined   undefined

[978 rows x 5 columns]

In [200]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Tags.csv', index = False, sep = '\t')

In [201]:
df = pd.read_csv(r'C:\Users\Denis\Downloads\PostLinks.csv', index_col=None, sep = ',', encoding = 'utf-8')

In [202]:
df

         _Id            _CreationDate  _PostId  _RelatedPostId  _LinkTypeId
0        103  2016-08-02T19:22:20.577      118              10            1
1        136  2016-08-02T21:18:16.763      140              36            1
2        179  2016-08-03T05:15:39.443      179              26            1
3        194  2016-08-03T06:20:50.550      148             186            1
4        195  2016-08-03T06:37:01.983       37              74            1
...      ...                      ...      ...             ...          ...
2105  461357  2022-09-06T13:06:13.103    36977           24157            1
2106  461358  2022-09-06T13:09:43.917    36975           18425            1
2107  461359  2022-09-06T13:09:43.917    36975           28291            1
2108  461360  2022-09-06T13:09:43.917    36975           24157            1
2109  461888  2022-09-10T17:59:04.687    37058           25178            1

[2110 rows x 5 columns]

In [203]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\PostLinks.csv', index = False, sep = '\t')

In [208]:
import xml.etree.ElementTree as Xet
import pandas as pd
import collections
  
cols = ['Id', "PostHistoryTypeId", 'PostId', "RevisionGUID", "CreationDate", "UserId", "Text", "ContentLicense"]
rows = []
  
# Parsing the XML file
xmlparse = Xet.parse(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\PostHistory.xml')
root = xmlparse.getroot()
for i in root:
    rows.append(i.attrib)

df = pd.DataFrame(rows, columns=cols)

In [209]:
df

,Id,PostHistoryTypeId,PostId,RevisionGUID,CreationDate,UserId,Text,ContentLicense
0,1,2,1,acd11026-43b5-4640-a6dd-dfff1749f5b5,2016-08-02T15:39:14.947,8,"What ""backprop"" does it mean? I've Googled it,...",CC BY-SA 3.0
1,2,1,1,acd11026-43b5-4640-a6dd-dfff1749f5b5,2016-08-02T15:39:14.947,8,"What is the ""backprop""?",CC BY-SA 3.0
2,3,3,1,acd11026-43b5-4640-a6dd-dfff1749f5b5,2016-08-02T15:39:14.947,8,<deep-network>,CC BY-SA 3.0
3,4,2,2,21760e2e-0597-45b4-bd0d-87a585d25a5e,2016-08-02T15:40:20.623,8,Does increasing noise would help to achieve be...,CC BY-SA 3.0
4,5,1,2,21760e2e-0597-45b4-bd0d-87a585d25a5e,2016-08-02T15:40:20.623,8,How does noise affect generalization?,CC BY-SA 3.0
...,...,...,...,...,...,...,...,...
90580,148320,2,37186,228c5cec-a936-4b52-b4b7-8e640481669a,2022-09-25T02:38:58.383,61270,I'm doing a machine learning project and was l...,CC BY-SA 4.0
90581,148322,1,37186,228c5cec-a936-4b52-b4b7-8e640481669a,2022-09-25T02:38:58.383,61270,Model Suggestions for Real Life local Hospital...,CC BY-SA 4.0
90582,148323,3,37186,228c5cec-a936-4b52-b4b7-8e640481669a,2022-09-25T02:38:58.383,61270,<machine-learning><training><models>,CC BY-SA 4.0
90583,148324,4,37186,046975ba-7165-44d0-b488-2e80c55b4aaf,2022-09-25T02:40:17.633,61270,Model Suggestions for Real Life local Hospital...,CC BY-SA 4.0
90584,148325,5,37186,5af0573f-cf50-4c59-be1d-afed57904614,2022-09-25T02:44:39.703,61270,I'm doing a machine learning project and was l...,CC BY-SA 4.0

In [210]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\PostHistory.csv', index = False, sep = '\t')

In [213]:
import xml.etree.ElementTree as Xet
import pandas as pd
import collections
  
cols = ['Id', "PostTypeId", "AcceptedAnswerId", "CreationDate", "Score", "ViewCount", "Body", 
        "OwnerUserId", 'LastEditorUserId', 'LastEditDate', 'LastActivityDate', 'Title', 'Tags', 'AnswerCount', 
       'CommentCount', 'FavoriteCount', 'ContentLicense']
rows = []
  
# Parsing the XML file
xmlparse = Xet.parse(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Posts.xml')
root = xmlparse.getroot()
for i in root:
    rows.append(i.attrib)

df = pd.DataFrame(rows, columns=cols)

In [214]:
df

,Id,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ContentLicense
0,1,1,3,2016-08-02T15:39:14.947,10,682,"<p>What does ""backprop"" mean? Is the ""backprop...",8,2444,2019-11-16T17:56:22.093,2021-07-08T10:45:23.250,"What is ""backprop""?",<neural-networks><backpropagation><terminology...,5,0,1,CC BY-SA 4.0
1,2,1,9,2016-08-02T15:40:20.623,14,960,<p>Does increasing the noise in data help to i...,8,2444,2019-02-23T22:36:19.090,2019-02-23T22:36:37.133,How does noise affect generalization?,<neural-networks><machine-learning><statistica...,3,0,2,CC BY-SA 4.0
2,3,2,NaN,2016-08-02T15:40:24.820,15,NaN,"<p>""Backprop"" is the same as ""backpropagation""...",4,NaN,NaN,2016-08-02T15:40:24.820,NaN,NaN,NaN,0,NaN,CC BY-SA 3.0
3,4,1,12,2016-08-02T15:41:22.020,33,1221,"<p>When you're writing your algorithm, how do ...",8,2444,2021-01-19T23:54:07.813,2021-01-19T23:54:07.813,How to find the optimal number of neurons per ...,<neural-networks><hyperparameter-optimization>...,4,0,11,CC BY-SA 3.0
4,6,1,20,2016-08-02T15:43:35.460,7,275,<p>Given the following definition of an intell...,29,2444,2019-06-15T18:25:58.513,2019-06-15T18:29:55.520,Are humans intelligent according to the defini...,<philosophy><definitions><intelligent-agent>,2,0,1,CC BY-SA 4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22467,37182,1,NaN,2022-09-24T11:34:39.800,0,8,<p>So i am trying to grasp the difference betw...,61238,NaN,NaN,2022-09-24T11:34:39.800,Utility function vs evaluation function vs heu...,<game-theory><alpha-beta-pruning><adversarial-...,0,0,NaN,CC BY-SA 4.0
22468,37183,2,NaN,2022-09-24T14:22:51.947,0,NaN,"<p>In my understanding , there could be multip...",10592,NaN,NaN,2022-09-24T14:22:51.947,NaN,NaN,NaN,0,NaN,CC BY-SA 4.0
22469,37184,2,NaN,2022-09-24T17:44:16.193,1,NaN,<p>I don't have a definitive answer but I'd st...,52211,NaN,NaN,2022-09-24T17:44:16.193,NaN,NaN,NaN,0,NaN,CC BY-SA 4.0
22470,37185,1,NaN,2022-09-25T02:23:46.747,0,3,"<p>Suppose that I use three features (x1, x2, ...",61269,NaN,NaN,2022-09-25T02:23:46.747,How to determine whether this situation belong...,<data-science><data-labelling>,0,0,NaN,CC BY-SA 4.0
22471,37186,1,NaN,2022-09-25T02:38:58.383,0,2,<p>I'm doing a machine learning project and wa...,61270,61270,2022-09-25T02:44:39.703,2022-09-25T02:44:39.703,Model Suggestions for Real Life local Hospital...,<machine-learning><training><models>,0,0,NaN,CC BY-SA 4.0

In [215]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Posts.csv', index = False, sep = '\t')

In [218]:
import xml.etree.ElementTree as Xet
import pandas as pd
import collections
  
cols = ['Id', "Reputation", "CreationDate", "DisplayName", "LastAccessDate", "Location", "AboutMe", 
        "Views", 'UpVotes', 'DownVotes', 'ProfileImageUrl', 'AccountId']
rows = []
  
# Parsing the XML file
xmlparse = Xet.parse(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Users.xml')
root = xmlparse.getroot()
for i in root:
    rows.append(i.attrib)

df = pd.DataFrame(rows, columns=cols)

In [219]:
df

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,1,101,2016-08-02T15:36:45.333,Adam Lear,2021-12-16T15:21:34.940,"New York, NY",\n<p>Developer at Stack Overflow focusing on p...,201,0,0,https://i.stack.imgur.com/A8wSd.jpg,37099
1,2,101,2016-08-02T15:36:48.397,Nick Craver,2016-11-30T22:09:22.300,"Winston-Salem, NC",<p>I am a Principal Software Engineer at Micro...,11,0,0,https://i.stack.imgur.com/nGCYr.jpg?s=128&g=1,7598
2,3,101,2016-08-02T15:38:01.633,Geoff Dalgas,2018-01-09T03:22:26.573,"Corvallis, OR, United States",<p>Dev #2 who helped create Stack Overflow cur...,12,0,0,https://i.stack.imgur.com/nDllk.png?s=128&g=1,2
3,4,2036,2016-08-02T15:38:21.100,Franck Dernoncourt,2022-08-01T02:17:27.473,NaN,"<p><a href=""https://stackexchange.com/users/16...",149,15,2,https://i.stack.imgur.com/Z99mk.jpg?s=128&g=1,169656
4,5,429,2016-08-02T15:38:27.643,baranskistad,2021-10-23T14:35:06.440,"Mankato, MN, United States",NaN,20,30,1,https://i.stack.imgur.com/Kk1s7.png?s=128&g=1,8057826
...,...,...,...,...,...,...,...,...,...,...,...,...
53127,61267,1,2022-09-25T01:27:40.830,Diego Domimguez,2022-09-25T01:27:40.830,NaN,NaN,0,0,0,https://lh3.googleusercontent.com/a-/ACNPEu9BA...,26434648
53128,61268,1,2022-09-25T02:12:52.400,Infomatec's,2022-09-25T03:01:36.227,NaN,NaN,0,0,0,NaN,26434792
53129,61269,1,2022-09-25T02:14:24.833,Zhang NaiChi,2022-09-25T02:14:24.833,NaN,NaN,0,0,0,https://lh3.googleusercontent.com/a/ALm5wu0p82...,26434798
53130,61270,1,2022-09-25T02:32:05.010,2 False,2022-09-25T02:32:05.010,NaN,NaN,0,0,0,https://lh6.googleusercontent.com/-01-tBNxj1rE...,15889206
53131,61271,1,2022-09-25T02:38:42.563,David Fertil,2022-09-25T02:38:42.563,NaN,NaN,0,0,0,https://lh3.googleusercontent.com/a/ALm5wu3Zg4...,26434886

In [220]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Users.csv', index = False, sep = '\t')

In [223]:
import xml.etree.ElementTree as Xet
import pandas as pd
import collections
  
cols = ['Id', "PostId", "VoteTypeId", "CreationDate"]
rows = []
  
# Parsing the XML file
xmlparse = Xet.parse(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Votes.xml')
root = xmlparse.getroot()
for i in root:
    rows.append(i.attrib)

df = pd.DataFrame(rows, columns=cols)

In [224]:
df

           Id PostId VoteTypeId             CreationDate
0           1      1          2  2016-08-02T00:00:00.000
1           2      1          2  2016-08-02T00:00:00.000
2           3      1          2  2016-08-02T00:00:00.000
3           4      1          2  2016-08-02T00:00:00.000
4           5      1          2  2016-08-02T00:00:00.000
...       ...    ...        ...                      ...
84525  104656  28245          5  2022-09-24T00:00:00.000
84526  104657  26336          2  2022-09-24T00:00:00.000
84527  104658  22831          2  2022-09-25T00:00:00.000
84528  104659   4489          2  2022-09-25T00:00:00.000
84529  104660  37184          2  2022-09-25T00:00:00.000

[84530 rows x 4 columns]

In [225]:
df.to_csv(r'C:\Users\Denis\Data Science\DataScience\University\Maga\DataBases\Project data\Votes.csv', index = False, sep = '\t')